### ISSUE TITLE
throwing compile error upon unexpected characters

### ISSUE THREAD

**Issue by walkermalling** [BinaryMuse/toml-require#1]
Getting compile errors on toml-require. Tested with the example toml text in the [toml](https://github.com/toml-lang/toml) readme.  

```
../node_modules/toml-require/index.js:25
        throw tomlCompileError;
              ^
Error: Error compiling ../config.toml at line 7, column 26: Expected "Z" but "-" found.
```

The line in the config referred to is:

`dob = 1979-05-27T07:32:00-08:00 # First class dates`

However, `toml-require` also threw this compile error 

```
../node_modules/toml-require/index.js:25
        throw tomlCompileError;
        ^

Error: Error compiling ../config.toml at line 3, column 11: Expected "-", "[", "\"", "false", "true", [ \t] or [0-9] but "'" found.
```

for the line:
`title = "Some title"`

Tried this in both node 0.12 and 4.0. The toml document was saved in UTF-8.  When I bypassed the toml-require and used fs.readFile to get the toml document to a parseable string, the `toml.parse` worked fine.

**Comment by BinaryMuse** [comment]
Give this a shot in the (just published) 1.1.0 and let me know how it works. It is less strict about the version of `toml` it bundles.

You can also pass your own instance of `toml` to `install()` now if you want; see the readme for the details.
